# Generated by Django 4.0.3 on 2022-03-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NFTs',
            new_name='NFT',
        ),
        migrations.RenameModel(
            old_name='NFTCollections',
            new_name='NFTCollection',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
