# Generated by Django 4.0.4 on 2022-07-20 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritednft',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Favorited'),
        ),
        migrations.AddField(
            model_name='userwatchlistednftcollection',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Watchlisted'),
        ),
    ]
