# Generated by Django 4.0.4 on 2022-05-04 20:04

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritednft',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Web.userfavoritednft'),
        ),
        migrations.AddField(
            model_name='userwatchlistednftcollection',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Web.userwatchlistednftcollection'),
        ),
    ]
