# Generated by Django 4.0.4 on 2022-05-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='file',
            new_name='nftFile',
        ),
    ]
