# Generated by Django 4.0.4 on 2022-07-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='address',
            new_name='collection',
        ),
        migrations.AlterUniqueTogether(
            name='nft',
            unique_together={('collection', 'nID')},
        ),
        migrations.RemoveField(
            model_name='nft',
            name='collectionName',
        ),
    ]
