# Generated by Django 4.0.4 on 2022-05-04 20:06

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_userfavoritednft_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Web.nft'),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Web.nftcollection'),
        ),
        migrations.AlterField(
            model_name='nftcollectioncategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Web.nftcollectioncategory'),
        ),
    ]
