# Generated by Django 4.0.4 on 2022-05-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_rename_file_nft_nftfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='nftFile',
            field=models.FileField(blank=True, null=True, upload_to='nfts/'),
        ),
    ]
