# Generated by Django 4.0.3 on 2022-04-02 17:34

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_rename_nfts_nft_rename_nftcollections_nftcollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Web.nft'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Web.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Category safe URL'),
        ),
    ]
