# Generated by Django 4.0.4 on 2022-05-02 19:53

import Web.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_alter_nft_nftfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='marketStatus',
        ),
        migrations.AlterField(
            model_name='nft',
            name='collectionName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectionName', to='Web.nftcollection', verbose_name='Collection Name'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='creatorName',
            field=models.ForeignKey(on_delete=models.SET('user_deleted'), related_name='creatorName', to='Web.user', to_field='username', verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='currentOwner',
            field=models.ForeignKey(on_delete=models.SET('user_deleted'), to='Web.user', to_field='username', verbose_name='Current Owner'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='nID',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='nftFile',
            field=models.FileField(blank=True, null=True, storage=Web.models.OverwriteStorage(), upload_to='nfts/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='uid',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
