# Generated by Django 4.0.4 on 2022-05-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_alter_nft_parent_alter_nftcollection_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
