# Generated by Django 4.0.3 on 2022-04-02 17:43

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_nft_parent_user_parent_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Web.nftcollection'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='dataLink',
            field=models.SlugField(verbose_name='Link of the content of NFT.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favoritedNFTs',
            field=models.ManyToManyField(blank=True, to='Web.nft'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchListedNFTCollections',
            field=models.ManyToManyField(blank=True, to='Web.nftcollection'),
        ),
    ]
