# Generated by Django 4.0.3 on 2022-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_remove_user_slug_nftcollection_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name="User's profile picture"),
        ),
    ]
