# Generated by Django 4.0.4 on 2022-05-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_alter_nft_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
