# Generated by Django 4.0.4 on 2022-05-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_remove_nft_marketstatus_alter_nft_collectionname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='marketStatus',
            field=models.IntegerField(choices=[(0, 'Not On Market'), (1, 'Not On Sale'), (2, 'On Sale')], default=0, verbose_name='Market Status'),
        ),
    ]
