# Generated by Django 4.0.4 on 2022-05-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_nft_marketstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='metaDataType',
            field=models.CharField(choices=[('video', 'video'), ('audio', 'audio'), ('image', 'image')], max_length=5, verbose_name='metadata type'),
        ),
    ]
