# Generated by Django 4.0.3 on 2022-04-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_alter_nft_options_remove_nft_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nft',
            options={},
        ),
    ]
