# Generated by Django 4.0.4 on 2022-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_alter_nft_collectionname_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mailAdress',
            field=models.EmailField(max_length=128, unique=True, verbose_name='Email'),
        ),
    ]
