# Generated by Django 4.0.4 on 2022-05-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_alter_user_mailadress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uAdress',
            new_name='uAddress',
        ),
    ]
