# Generated by Django 4.0.3 on 2022-04-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_nft_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Category safe URL'),
        ),
    ]
