# Generated by Django 4.0.4 on 2022-05-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_rename_uadress_user_uaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mailAdress',
            new_name='mailAddress',
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
