# Generated by Django 4.0.4 on 2022-05-02 21:45

import Web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_rename_mailadress_user_mailaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='collectionImage',
            field=models.ImageField(blank=True, null=True, storage=Web.models.OverwriteStorage(), upload_to=Web.models.FileUploadLocation(fields=['name'], parentFolder='NFTCollections/'), verbose_name='Collection Image'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='dataLink',
            field=models.URLField(verbose_name='Data Link'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='metaDataType',
            field=models.CharField(choices=[('video', 'video'), ('audio', 'audio'), ('image', 'image')], max_length=5, verbose_name='Metadata Type'),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='owner',
            field=models.ForeignKey(default='', on_delete=models.SET('user_deleted'), related_name='owner', to='Web.user', to_field='username', verbose_name='Name'),
        ),
    ]
