# Generated by Django 4.0.3 on 2022-04-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_remove_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='0', max_length=100, verbose_name='Password of user'),
        ),
    ]
