# Generated by Django 4.0.3 on 2022-04-19 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='marketStatus',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='0: not on market, 1: on market but not on sale, 2: on market and on sale'),
        ),
    ]
