# Generated by Django 4.0.3 on 2022-04-19 16:14

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0012_alter_nft_marketstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='description',
            field=models.TextField(null=True, verbose_name='Description of the NFT given by the creator.'),
        ),
        migrations.CreateModel(
            name='NFTCollectionCategory',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Name of the NFT Collection Category.')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Web.nftcollectioncategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
