# Generated by Django 4.0.3 on 2022-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0013_nftcollection_description_nftcollectioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='category',
            field=models.ForeignKey(default='', on_delete=models.SET('user_deleted'), related_name='category', to='Web.nftcollectioncategory', verbose_name='Category of the NFT Collection.'),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='owner',
            field=models.ForeignKey(default='', on_delete=models.SET('user_deleted'), related_name='owner', to='Web.user', to_field='username', verbose_name='Name of the creator of the NFT Collection.'),
        ),
    ]
